{
"options" : {
  "pcb-thickness" : 0.8,
  "alpha" : 0.01,
  "pcb-alpha": 0.09,
  "alpha-density": 1,
  "pcb-tolerance" : 0.5,
  "pcb-tolerance-z" : 0.1,
  "bot-thickness" : 7.3,
  "top-thickness" : 5,
  "corner-type" : "cylinder",
  "segments" : 20,
  "lid-tolerance" : 0.15,
  "lid-thickness" : 1.5,
  "strut-height-adjust": 0.5,
},

"layout":
[
  [ # row 0
    # col 0
    "
    rect(5, 5, h=1.4, x=6, loc=br);
    rect(11, 11, h=0.9, z=0.6,x=10, top=false, lid=true, loc=br);
    screw(0.0, head_d=9, head_h=1.0, shaft_h=4.6, top=false,pcb=false,cone=true)
    ",

    # col 1
    "usb_c(y=0, z=+0.8, loc=tr)",

    # col 2
    "
    hex(4.8, r=30, h=3.5, lid=false, loc=br);
    screw('m3', head_h=2.3, shaft_d=11, shaft_h=4.6, top=false,pcb=false,loc=br,cone=true)
    ",

    # col 3
    "usb_c(y=0, z=+0.8, loc=tr)",

    # col 4
    "",

    # col 5
    "screw(0.0, head_d=9, head_h=1.0, shaft_h=4.6, top=false,pcb=false,cone=true)"
  ],
  [ #row 1
    # col 0, screw hole
    "
    hex(4.8, r=30, h=3.5, lid=false,loc=br);
    screw('m3', head_h=2.3, shaft_d=11, shaft_h=4.6, top=false,pcb=false,loc=br,cone=true)
    ",

    # col 1, power switch
    "
      rect(7, 5, h=1.4,loc=br);
      rect(4.5, 2.5, h=1.5,lid=true,top=false,loc=br, scalex=-1.7, scaley=1.5);
    ",

    # col 2
    "",

    # col 3, hole for cr2032 battery leg
    "rect(7, 5, h=1.4,loc=br);",

    "
    hex(4.8, r=30, h=3.5, lid=false,loc=br);
    screw('m3', head_h=2.3, shaft_d=11, shaft_h=4.6, top=false, pcb=false, loc=br, cone=true);
    screw(1.5, y=-1.0, top=false,pcb=false, loc=cl);
    rect(5, 5, y=-1.0, z=1.0, lid=true,top=false,pcb=false, loc=cl)",
    ""
  ],
  [
    # col 0
    "",
    # col 1
    "rect(3, 5, h=2.3, x=-1.4, loc=bc)",

    # col 2
    "
    rect(30.5,20,h=10, z=0.6, top=false,lid=true,loc=bl);
    hex(4.8, r=30, h=3.5, lid=false,loc=br);
    screw('m3', head_h=2.3, shaft_d=11, shaft_h=4.6, top=false, pcb=false, loc=br, cone=true);
    rect(3, 5, h=2.3, x=+1.4,loc=bc)
    ",

    "",
    "",
    ""
  ],
  [
    # col 0
    "screw(0.0, head_d=9, head_h=1.0, shaft_h=4.6, top=false,pcb=false,cone=true)",
    "",
    "",
    "",
    "",
    # col 5
    "screw(0.0, head_d=9, head_h=1.0, shaft_h=4.6, top=false,pcb=false,cone=true)"
  ]
]
}
