{
"options" : {
  "pcb-thickness" : 1.6,
  "pcb-tolerance" : 0.5,
  "pcb-tolerance-z" : 0.1,
  "bot-thickness" : 8.0,
  "top-thickness" : 5,
  "corner-type" : "cylinder",
  "segments" : 20,
  "margin" : 2.5,
  "lid-tolerance" : 0.15,
  "lid-thickness" : 1.5,
  "strut-height-adjust": 0.5,
  "xcuts": "3.0 9.0",
},

"layout":
[
  [
    {
      "a": 7
    },
    "
    hex(4.8, r=30, h=3.5, lid=false,loc=cr);
    screw('m3', head_h=2.3, shaft_d=11, shaft_h=2.5, top=false, pcb=false, loc=cr, cone=true);
    ",
    "",
    "",
    "",
    "",
    "usb_c(y=0, z=+0.0, loc=tr)",
    "",
    "",
    "",
    "",
    "",
    "
    hex(4.8, r=30, h=3.5, lid=false,loc=cl);
    screw('m3', head_h=2.3, shaft_d=11, shaft_h=2.5, top=false, pcb=false, loc=cl, cone=true);
    "
  ],
  [
    "",
    "",
    "",
    "
    hex(4.8, r=30, h=3.5, lid=false,loc=cr);
    screw('m3', head_h=2.3, shaft_d=11, shaft_h=2.5, top=false, pcb=false, loc=cr, cone=true);
    ",
    "",
    "",
    "",
    "
    hex(4.8, r=30, h=3.5, lid=false,loc=cr);
    screw('m3', head_h=2.3, shaft_d=11, shaft_h=2.5, top=false, pcb=false, loc=cr, cone=true);
    ",
    "",
    "",
    "",
    ""
  ],
  [
    "",
    "",
    "",
    "
    hex(4.8, r=30, h=3.5, lid=false,loc=cr);
    screw('m3', head_h=2.3, shaft_d=11, shaft_h=2.5, top=false, pcb=false, loc=cr, cone=true);
    ",
    "",
    "",
    "",
    "
    hex(4.8, r=30, h=3.5, lid=false,loc=cr);
    screw('m3', head_h=2.3, shaft_d=11, shaft_h=2.5, top=false, pcb=false, loc=cr, cone=true);
    ",
    "",
    "",
    "",
    ""
  ],
  [
    "
    hex(4.8, r=30, h=3.5, lid=false,loc=cr);
    screw('m3', head_h=2.3, shaft_d=11, shaft_h=2.5, top=false, pcb=false, loc=cr, cone=true);
    ",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "
    hex(4.8, r=30, h=3.5, lid=false,loc=cl);
    screw('m3', head_h=2.3, shaft_d=11, shaft_h=2.5, top=false, pcb=false, loc=cl, cone=true);
    "
  ]
]
}
